# Generated by Django 4.2.17 on 2025-01-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DSE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('Role', models.CharField(max_length=100)),
                ('Normalshifts', models.BooleanField()),
                ('nightshifts', models.BooleanField()),
                ('oncall', models.BooleanField()),
                ('eveningshifts', models.BooleanField()),
                ('ER', models.BooleanField()),
                ('sundaymorning', models.BooleanField()),
                ('earlyshifts', models.BooleanField()),
                ('mondaytofriday', models.BooleanField()),
            ],
        ),
    ]
